import { useState } from 'react';
import type { ConfirmationRequest, Message } from '../types/audit';
import { relatedCases } from '../lib/evidence';
export function ConfirmationForm({message,onConfirm,busy,error}:{message:Message;onConfirm:(r:ConfirmationRequest)=>void;busy:boolean;error:string}) {
  const analysis=message.analysis!;
  const [decision,setDecision]=useState<ConfirmationRequest['decision']>('confirm_recurrence');
  const [analyst,setAnalyst]=useState('');const [root,setRoot]=useState(analysis.previous_root_cause?.text||'');const [remediation,setRemediation]=useState(analysis.previous_remediation?.text||'');
  const [outcome,setOutcome]=useState<ConfirmationRequest['outcome']>('open');const [note,setNote]=useState('');
  const candidates=relatedCases(analysis);
  const [linked,setLinked]=useState(candidates.filter(c=>c.is_recurrence_candidate).map(c=>c.finding_id));
  return <form className="dialog-form" onSubmit={e=>{e.preventDefault();if(!busy)onConfirm({analysis_id:analysis.analysis_id,decision,linked_finding_ids:linked,confirmed_root_cause:root.trim()||null,confirmed_remediation:remediation.trim()||null,outcome,analyst:analyst.trim(),note:note.trim()||null});}}><p className="dialog-description">Review or correct the proposed interpretation. Only your confirmed outcome is submitted as verified history.</p><label>Decision<select value={decision} onChange={e=>setDecision(e.target.value as ConfirmationRequest['decision'])}><option value="confirm_recurrence">Confirm recurrence</option><option value="correct">Correct the analysis</option><option value="not_recurrence">Not a recurrence</option></select></label>{!!candidates.length&&<fieldset><legend>Related findings</legend>{candidates.map(c=><label className="checkbox-label" key={c.finding_id}><input type="checkbox" checked={linked.includes(c.finding_id)} onChange={e=>setLinked(v=>e.target.checked?[...v,c.finding_id]:v.filter(id=>id!==c.finding_id))}/>{c.finding_id}</label>)}</fieldset>}<label>Confirmed root cause{decision!=='not_recurrence'&&<span className="required">Required</span>}<textarea rows={3} required={decision!=='not_recurrence'} value={root} onChange={e=>setRoot(e.target.value)} placeholder="Describe the verified root cause"/></label><label>Confirmed remediation<textarea rows={2} value={remediation} onChange={e=>setRemediation(e.target.value)} placeholder="Describe the agreed remediation"/></label><div className="form-columns"><label>Outcome<select value={outcome} onChange={e=>setOutcome(e.target.value as ConfirmationRequest['outcome'])}><option value="open">Open</option><option value="remediated_with_evidence">Remediated with evidence</option><option value="remediated_no_evidence">Remediated without evidence</option><option value="accepted_risk">Accepted risk</option></select></label><label>Analyst name<input required value={analyst} onChange={e=>setAnalyst(e.target.value)} placeholder="Your name"/></label></div><label>Note <span className="optional">Optional</span><textarea rows={2} value={note} onChange={e=>setNote(e.target.value)} placeholder="Additional context or corrections"/></label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="primary-button" disabled={busy||!analyst.trim()||(decision!=='not_recurrence'&&!root.trim())}>{busy?'Submitting confirmation…':'Confirm & retain verified outcome'}</button></form>;
}
